// Copyright 2019 Atharva Pandey. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found
// in the LICENSE file.

package gountry

//Timezones contains data mapping for timezone country name and country capital and continental region
var Timezones = []TimezoneType{
	{
		Timezones: []string{"Europe/Andorra"},
		Code:      "AD",
		Continent: "Europe",
		Name:      "Andorra",
		Capital:   "Andorra la Vella",
	},
	{
		Timezones: []string{"Asia/Kabul"},
		Code:      "AF",
		Continent: "Asia",
		Name:      "Afghanistan",
		Capital:   "Kabul"},
	{
		Timezones: []string{"America/Antigua"},
		Code:      "AG",
		Continent: "North America",
		Name:      "Antigua and Barbuda",
		Capital:   "St. John's"},
	{
		Timezones: []string{"Europe/Tirane"},
		Code:      "AL",
		Continent: "Europe",
		Name:      "Albania",
		Capital:   "Tirana"},
	{
		Timezones: []string{"Asia/Yerevan"},
		Code:      "AM",
		Continent: "Asia",
		Name:      "Armenia",
		Capital:   "Yerevan"},
	{
		Timezones: []string{"Africa/Luanda"},
		Code:      "AO",
		Continent: "Africa",
		Name:      "Angola",
		Capital:   "Luanda"},
	{
		Timezones: []string{"America/Argentina/Buenos_Aires", "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/Tucuman", "America/Argentina/Catamarca", "America/Argentina/La_Rioja", "America/Argentina/San_Juan", "America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos", "America/Argentina/Ushuaia"},
		Code:      "AR",
		Continent: "South America",
		Name:      "Argentina",
		Capital:   "Buenos Aires"},
	{
		Timezones: []string{"Europe/Vienna"},
		Code:      "AT",
		Continent: "Europe",
		Name:      "Austria",
		Capital:   "Vienna"},
	{
		Timezones: []string{"Australia/Lord_Howe", "Australia/Hobart", "Australia/Currie", "Australia/Melbourne", "Australia/Sydney", "Australia/Broken_Hill", "Australia/Brisbane", "Australia/Lindeman", "Australia/Adelaide", "Australia/Darwin", "Australia/Perth"},
		Code:      "AU",
		Continent: "Oceania",
		Name:      "Australia",
		Capital:   "Canberra"},
	{
		Timezones: []string{"Asia/Baku"},
		Code:      "AZ",
		Continent: "Asia",
		Name:      "Azerbaijan",
		Capital:   "Baku"},
	{
		Timezones: []string{"America/Barbados"},
		Code:      "BB",
		Continent: "North America",
		Name:      "Barbados",
		Capital:   "Bridgetown"},
	{
		Timezones: []string{"Asia/Dhaka"},
		Code:      "BD",
		Continent: "Asia",
		Name:      "Bangladesh",
		Capital:   "Dhaka"},
	{
		Timezones: []string{"Europe/Brussels"},
		Code:      "BE",
		Continent: "Europe",
		Name:      "Belgium",
		Capital:   "Brussels"},
	{
		Timezones: []string{"Africa/Ouagadougou"},
		Code:      "BF",
		Continent: "Africa",
		Name:      "Burkina Faso",
		Capital:   "Ouagadougou"},
	{
		Timezones: []string{"Europe/Sofia"},
		Code:      "BG",
		Continent: "Europe",
		Name:      "Bulgaria",
		Capital:   "Sofia"},
	{
		Timezones: []string{"Asia/Bahrain"},
		Code:      "BH",
		Continent: "Asia",
		Name:      "Bahrain",
		Capital:   "Manama"},
	{
		Timezones: []string{"Africa/Bujumbura"},
		Code:      "BI",
		Continent: "Africa",
		Name:      "Burundi",
		Capital:   "Bujumbura"},
	{
		Timezones: []string{"Africa/Porto-Novo"},
		Code:      "BJ",
		Continent: "Africa",
		Name:      "Benin",
		Capital:   "Porto-Novo"},
	{
		Timezones: []string{"Asia/Brunei"},
		Code:      "BN",
		Continent: "Asia",
		Name:      "Brunei Darussalam",
		Capital:   "Bandar Seri Begawan"},
	{
		Timezones: []string{"America/La_Paz"},
		Code:      "BO",
		Continent: "South America",
		Name:      "Bolivia",
		Capital:   "Sucre"},
	{
		Timezones: []string{"America/Noronha", "America/Belem", "America/Fortaleza", "America/Recife", "America/Araguaina", "America/Maceio", "America/Bahia", "America/Sao_Paulo", "America/Campo_Grande", "America/Cuiaba", "America/Porto_Velho", "America/Boa_Vista", "America/Manaus", "America/Eirunepe", "America/Rio_Branco"},
		Code:      "BR",
		Continent: "South America",
		Name:      "Brazil",
		Capital:   "Brasília"},
	{
		Timezones: []string{"America/Nassau"},
		Code:      "BS",
		Continent: "North America",
		Name:      "Bahamas",
		Capital:   "Nassau"},
	{
		Timezones: []string{"Asia/Thimphu"},
		Code:      "BT",
		Continent: "Asia",
		Name:      "Bhutan",
		Capital:   "Thimphu"},
	{
		Timezones: []string{"Africa/Gaborone"},
		Code:      "BW",
		Continent: "Africa",
		Name:      "Botswana",
		Capital:   "Gaborone"},
	{
		Timezones: []string{"Europe/Minsk"},
		Code:      "BY",
		Continent: "Europe",
		Name:      "Belarus",
		Capital:   "Minsk"},
	{
		Timezones: []string{"America/Belize"},
		Code:      "BZ",
		Continent: "North America",
		Name:      "Belize",
		Capital:   "Belmopan"},
	{
		Timezones: []string{"America/St_Johns", "America/Halifax", "America/Glace_Bay", "America/Moncton", "America/Goose_Bay", "America/Blanc-Sablon", "America/Montreal", "America/Toronto", "America/Nipigon", "America/Thunder_Bay", "America/Pangnirtung", "America/Iqaluit", "America/Atikokan", "America/Rankin_Inlet", "America/Winnipeg", "America/Rainy_River", "America/Cambridge_Bay", "America/Regina", "America/Swift_Current", "America/Edmonton", "America/Yellowknife", "America/Inuvik", "America/Dawson_Creek", "America/Vancouver", "America/Whitehorse", "America/Dawson"},
		Code:      "CA",
		Continent: "North America",
		Name:      "Canada",
		Capital:   "Ottawa"},
	{
		Timezones: []string{"Africa/Kinshasa", "Africa/Lubumbashi"},
		Code:      "CD",
		Continent: "Africa",
		Name:      "Democratic Republic of the Congo",
		Capital:   "Kinshasa"},
	{
		Timezones: []string{"Africa/Brazzaville"},
		Code:      "CG",
		Continent: "Africa",
		Name:      "Republic of the Congo",
		Capital:   "Brazzaville"},
	{
		Timezones: []string{"Africa/Abidjan"},
		Code:      "CI",
		Continent: "Africa",
		Name:      "Ivory Coast",
		Capital:   "Yamoussoukro"},
	{
		Timezones: []string{"America/Santiago", "Pacific/Easter"},
		Code:      "CL",
		Continent: "South America",
		Name:      "Chile",
		Capital:   "Santiago"},
	{
		Timezones: []string{"Africa/Douala"},
		Code:      "CM",
		Continent: "Africa",
		Name:      "Cameroon",
		Capital:   "Yaoundé"},
	{
		Timezones: []string{"Asia/Shanghai", "Asia/Harbin", "Asia/Chongqing", "Asia/Urumqi", "Asia/Kashgar"},
		Code:      "CN",
		Continent: "Asia",
		Name:      "People's Republic of China",
		Capital:   "Beijing"},
	{
		Timezones: []string{"America/Bogota"},
		Code:      "CO",
		Continent: "South America",
		Name:      "Colombia",
		Capital:   "Bogotá"},
	{
		Timezones: []string{"America/Costa_Rica"},
		Code:      "CR",
		Continent: "North America",
		Name:      "Costa Rica",
		Capital:   "San José"},
	{
		Timezones: []string{"America/Havana"},
		Code:      "CU",
		Continent: "North America",
		Name:      "Cuba",
		Capital:   "Havana"},
	{
		Timezones: []string{"Atlantic/Cape_Verde"},
		Code:      "CV",
		Continent: "Africa",
		Name:      "Cape Verde",
		Capital:   "Praia"},
	{
		Timezones: []string{"Asia/Nicosia"},
		Code:      "CY",
		Continent: "Asia",
		Name:      "Cyprus",
		Capital:   "Nicosia"},
	{
		Timezones: []string{"Europe/Prague"},
		Code:      "CZ",
		Continent: "Europe",
		Name:      "Czech Republic",
		Capital:   "Prague"},
	{
		Timezones: []string{"Europe/Berlin"},
		Code:      "DE",
		Continent: "Europe",
		Name:      "Germany",
		Capital:   "Berlin"},
	{
		Timezones: []string{"Africa/Djibouti"},
		Code:      "DJ",
		Continent: "Africa",
		Name:      "Djibouti",
		Capital:   "Djibouti City"},
	{
		Timezones: []string{"Europe/Copenhagen"},
		Code:      "DK",
		Continent: "Europe",
		Name:      "Denmark",
		Capital:   "Copenhagen"},
	{
		Timezones: []string{"America/Dominica"},
		Code:      "DM",
		Continent: "North America",
		Name:      "Dominica",
		Capital:   "Roseau"},
	{
		Timezones: []string{"America/Santo_Domingo"},
		Code:      "DO",
		Continent: "North America",
		Name:      "Dominican Republic",
		Capital:   "Santo Domingo"},
	{
		Timezones: []string{"America/Guayaquil", "Pacific/Galapagos"},
		Code:      "EC",
		Continent: "South America",
		Name:      "Ecuador",
		Capital:   "Quito"},
	{
		Timezones: []string{"Europe/Tallinn"},
		Code:      "EE",
		Continent: "Europe",
		Name:      "Estonia",
		Capital:   "Tallinn"},
	{
		Timezones: []string{"Africa/Cairo"},
		Code:      "EG",
		Continent: "Africa",
		Name:      "Egypt",
		Capital:   "Cairo"},
	{
		Timezones: []string{"Africa/Asmera"},
		Code:      "ER",
		Continent: "Africa",
		Name:      "Eritrea",
		Capital:   "Asmara"},
	{
		Timezones: []string{"Africa/Addis_Ababa"},
		Code:      "ET",
		Continent: "Africa",
		Name:      "Ethiopia",
		Capital:   "Addis Ababa"},
	{
		Timezones: []string{"Europe/Helsinki"},
		Code:      "FI",
		Continent: "Europe",
		Name:      "Finland",
		Capital:   "Helsinki"},
	{
		Timezones: []string{"Pacific/Fiji"},
		Code:      "FJ",
		Continent: "Oceania",
		Name:      "Fiji",
		Capital:   "Suva"},
	{
		Timezones: []string{"Europe/Paris"},
		Code:      "FR",
		Continent: "Europe",
		Name:      "France",
		Capital:   "Paris"},
	{
		Timezones: []string{"Africa/Libreville"},
		Code:      "GA",
		Continent: "Africa",
		Name:      "Gabon",
		Capital:   "Libreville"},
	{
		Timezones: []string{"Asia/Tbilisi"},
		Code:      "GE",
		Continent: "Asia",
		Name:      "Georgia",
		Capital:   "Tbilisi"},
	{
		Timezones: []string{"Africa/Accra"},
		Code:      "GH",
		Continent: "Africa",
		Name:      "Ghana",
		Capital:   "Accra"},
	{
		Timezones: []string{"Africa/Banjul"},
		Code:      "GM",
		Continent: "Africa",
		Name:      "The Gambia",
		Capital:   "Banjul"},
	{
		Timezones: []string{"Africa/Conakry"},
		Code:      "GN",
		Continent: "Africa",
		Name:      "Guinea",
		Capital:   "Conakry"},
	{
		Timezones: []string{"Europe/Athens"},
		Code:      "GR",
		Continent: "Europe",
		Name:      "Greece",
		Capital:   "Athens"},
	{
		Timezones: []string{"America/Guatemala"},
		Code:      "GT",
		Continent: "North America",
		Name:      "Guatemala",
		Capital:   "Guatemala City"},
	{
		Timezones: []string{"America/Guatemala"},
		Code:      "HT",
		Continent: "North America",
		Name:      "Haiti",
		Capital:   "Port-au-Prince"},
	{
		Timezones: []string{"Africa/Bissau"},
		Code:      "GW",
		Continent: "Africa",
		Name:      "Guinea-Bissau",
		Capital:   "Bissau"},
	{
		Timezones: []string{"America/Guyana"},
		Code:      "GY",
		Continent: "South America",
		Name:      "Guyana",
		Capital:   "Georgetown"},
	{
		Timezones: []string{"America/Tegucigalpa"},
		Code:      "HN",
		Continent: "North America",
		Name:      "Honduras",
		Capital:   "Tegucigalpa"},
	{
		Timezones: []string{"Europe/Budapest"},
		Code:      "HU",
		Continent: "Europe",
		Name:      "Hungary",
		Capital:   "Budapest"},
	{
		Timezones: []string{"Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"},
		Code:      "ID",
		Continent: "Asia",
		Name:      "Indonesia",
		Capital:   "Jakarta"},
	{
		Timezones: []string{"Europe/Dublin"},
		Code:      "IE",
		Continent: "Europe",
		Name:      "Republic of Ireland",
		Capital:   "Dublin"},
	{
		Timezones: []string{"Asia/Jerusalem"},
		Code:      "IL",
		Continent: "Asia",
		Name:      "Israel",
		Capital:   "Jerusalem"},
	{
		Timezones: []string{"Asia/Calcutta"},
		Code:      "IN",
		Continent: "Asia",
		Name:      "India",
		Capital:   "New Delhi"},
	{
		Timezones: []string{"Asia/Baghdad"},
		Code:      "IQ",
		Continent: "Asia",
		Name:      "Iraq",
		Capital:   "Baghdad"},
	{
		Timezones: []string{"Asia/Tehran"},
		Code:      "IR",
		Continent: "Asia",
		Name:      "Iran",
		Capital:   "Tehran"},
	{
		Timezones: []string{"Atlantic/Reykjavik"},
		Code:      "IS",
		Continent: "Europe",
		Name:      "Iceland",
		Capital:   "Reykjavik"},
	{
		Timezones: []string{"Europe/Rome"},
		Code:      "IT",
		Continent: "Europe",
		Name:      "Italy",
		Capital:   "Rome"},
	{
		Timezones: []string{"America/Jamaica"},
		Code:      "JM",
		Continent: "North America",
		Name:      "Jamaica",
		Capital:   "Kingston"},
	{
		Timezones: []string{"Asia/Amman"},
		Code:      "JO",
		Continent: "Asia",
		Name:      "Jordan",
		Capital:   "Amman"},
	{
		Timezones: []string{"Asia/Tokyo"},
		Code:      "JP",
		Continent: "Asia",
		Name:      "Japan",
		Capital:   "Tokyo"},
	{
		Timezones: []string{"Africa/Nairobi"},
		Code:      "KE",
		Continent: "Africa",
		Name:      "Kenya",
		Capital:   "Nairobi"},
	{
		Timezones: []string{"Asia/Bishkek"},
		Code:      "KG",
		Continent: "Asia",
		Name:      "Kyrgyzstan",
		Capital:   "Bishkek"},
	{
		Timezones: []string{"Pacific/Tarawa", "Pacific/Enderbury", "Pacific/Kiritimati"},
		Code:      "KI",
		Continent: "Oceania",
		Name:      "Kiribati",
		Capital:   "Tarawa"},
	{
		Timezones: []string{"Asia/Pyongyang"},
		Code:      "KP",
		Continent: "Asia",
		Name:      "North Korea",
		Capital:   "Pyongyang"},
	{
		Timezones: []string{"Asia/Seoul"},
		Code:      "KR",
		Continent: "Asia",
		Name:      "South Korea",
		Capital:   "Seoul"},
	{
		Timezones: []string{"Asia/Kuwait"},
		Code:      "KW",
		Continent: "Asia",
		Name:      "Kuwait",
		Capital:   "Kuwait City"},
	{
		Timezones: []string{"Asia/Beirut"},
		Code:      "LB",
		Continent: "Asia",
		Name:      "Lebanon",
		Capital:   "Beirut"},
	{
		Timezones: []string{"Europe/Vaduz"},
		Code:      "LI",
		Continent: "Europe",
		Name:      "Liechtenstein",
		Capital:   "Vaduz"},
	{
		Timezones: []string{"Africa/Monrovia"},
		Code:      "LR",
		Continent: "Africa",
		Name:      "Liberia",
		Capital:   "Monrovia"},
	{
		Timezones: []string{"Africa/Maseru"},
		Code:      "LS",
		Continent: "Africa",
		Name:      "Lesotho",
		Capital:   "Maseru"},
	{
		Timezones: []string{"Europe/Vilnius"},
		Code:      "LT",
		Continent: "Europe",
		Name:      "Lithuania",
		Capital:   "Vilnius"},
	{
		Timezones: []string{"Europe/Luxembourg"},
		Code:      "LU",
		Continent: "Europe",
		Name:      "Luxembourg",
		Capital:   "Luxembourg City"},
	{
		Timezones: []string{"Europe/Riga"},
		Code:      "LV",
		Continent: "Europe",
		Name:      "Latvia",
		Capital:   "Riga"},
	{
		Timezones: []string{"Africa/Tripoli"},
		Code:      "LY",
		Continent: "Africa",
		Name:      "Libya",
		Capital:   "Tripoli"},
	{
		Timezones: []string{"Indian/Antananarivo"},
		Code:      "MG",
		Continent: "Africa",
		Name:      "Madagascar",
		Capital:   "Antananarivo"},
	{
		Timezones: []string{"Pacific/Majuro", "Pacific/Kwajalein"},
		Code:      "MH",
		Continent: "Oceania",
		Name:      "Marshall Islands",
		Capital:   "Majuro"},
	{
		Timezones: []string{"Europe/Skopje"},
		Code:      "MK",
		Continent: "Europe",
		Name:      "Macedonia",
		Capital:   "Skopje"},
	{
		Timezones: []string{"Africa/Bamako"},
		Code:      "ML",
		Continent: "Africa",
		Name:      "Mali",
		Capital:   "Bamako"},
	{
		Timezones: []string{"Asia/Rangoon"},
		Code:      "MM",
		Continent: "Asia",
		Name:      "Myanmar",
		Capital:   "Naypyidaw"},
	{
		Timezones: []string{"Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"},
		Code:      "MN",
		Continent: "Asia",
		Name:      "Mongolia",
		Capital:   "Ulaanbaatar"},
	{
		Timezones: []string{"Africa/Nouakchott"},
		Code:      "MR",
		Continent: "Africa",
		Name:      "Mauritania",
		Capital:   "Nouakchott"},
	{
		Timezones: []string{"Europe/Malta"},
		Code:      "MT",
		Continent: "Europe",
		Name:      "Malta",
		Capital:   "Valletta"},
	{
		Timezones: []string{"Indian/Mauritius"},
		Code:      "MU",
		Continent: "Africa",
		Name:      "Mauritius",
		Capital:   "Port Louis"},
	{
		Timezones: []string{"Indian/Maldives"},
		Code:      "MV",
		Continent: "Asia",
		Name:      "Maldives",
		Capital:   "Malé"},
	{
		Timezones: []string{"Africa/Blantyre"},
		Code:      "MW",
		Continent: "Africa",
		Name:      "Malawi",
		Capital:   "Lilongwe"},
	{
		Timezones: []string{"America/Mexico_City", "America/Cancun", "America/Merida", "America/Monterrey", "America/Mazatlan", "America/Chihuahua", "America/Hermosillo", "America/Tijuana"},
		Code:      "MX",
		Continent: "North America",
		Name:      "Mexico",
		Capital:   "Mexico City"},
	{
		Timezones: []string{"Asia/Kuala_Lumpur", "Asia/Kuching"},
		Code:      "MY",
		Continent: "Asia",
		Name:      "Malaysia",
		Capital:   "Kuala Lumpur"},
	{
		Timezones: []string{"Africa/Maputo"},
		Code:      "MZ",
		Continent: "Africa",
		Name:      "Mozambique",
		Capital:   "Maputo"},
	{
		Timezones: []string{"Africa/Windhoek"},
		Code:      "NA",
		Continent: "Africa",
		Name:      "Namibia",
		Capital:   "Windhoek"},
	{
		Timezones: []string{"Africa/Niamey"},
		Code:      "NE",
		Continent: "Africa",
		Name:      "Niger",
		Capital:   "Niamey"},
	{
		Timezones: []string{"Africa/Lagos"},
		Code:      "NG",
		Continent: "Africa",
		Name:      "Nigeria",
		Capital:   "Abuja"},
	{
		Timezones: []string{"America/Managua"},
		Code:      "NI",
		Continent: "North America",
		Name:      "Nicaragua",
		Capital:   "Managua"},
	{
		Timezones: []string{"Europe/Amsterdam"},
		Code:      "NL",
		Continent: "Europe",
		Name:      "Kingdom of the Netherlands",
		Capital:   "Amsterdam"},
	{
		Timezones: []string{"Europe/Oslo"},
		Code:      "NO",
		Continent: "Europe",
		Name:      "Norway",
		Capital:   "Oslo"},
	{
		Timezones: []string{"Asia/Katmandu"},
		Code:      "NP",
		Continent: "Asia",
		Name:      "Nepal",
		Capital:   "Kathmandu"},
	{
		Timezones: []string{"Pacific/Nauru"},
		Code:      "NR",
		Continent: "Oceania",
		Name:      "Nauru",
		Capital:   "Yaren"},
	{
		Timezones: []string{"Pacific/Auckland", "Pacific/Chatham"},
		Code:      "NZ",
		Continent: "Oceania",
		Name:      "New Zealand",
		Capital:   "Wellington"},
	{
		Timezones: []string{"Asia/Muscat"},
		Code:      "OM",
		Continent: "Asia",
		Name:      "Oman",
		Capital:   "Muscat"},
	{
		Timezones: []string{"America/Panama"},
		Code:      "PA",
		Continent: "North America",
		Name:      "Panama",
		Capital:   "Panama City"},
	{
		Timezones: []string{"America/Lima"},
		Code:      "PE",
		Continent: "South America",
		Name:      "Peru",
		Capital:   "Lima"},
	{
		Timezones: []string{"Pacific/Port_Moresby"},
		Code:      "PG",
		Continent: "Oceania",
		Name:      "Papua New Guinea",
		Capital:   "Port Moresby"},
	{
		Timezones: []string{"Asia/Manila"},
		Code:      "PH",
		Continent: "Asia",
		Name:      "Philippines",
		Capital:   "Manila"},
	{
		Timezones: []string{"Asia/Karachi"},
		Code:      "PK",
		Continent: "Asia",
		Name:      "Pakistan",
		Capital:   "Islamabad"},
	{
		Timezones: []string{"Europe/Warsaw"},
		Code:      "PL",
		Continent: "Europe",
		Name:      "Poland",
		Capital:   "Warsaw"},
	{
		Timezones: []string{"Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"},
		Code:      "PT",
		Continent: "Europe",
		Name:      "Portugal",
		Capital:   "Lisbon"},
	{
		Timezones: []string{"Pacific/Palau"},
		Code:      "PW",
		Continent: "Oceania",
		Name:      "Palau",
		Capital:   "Ngerulmud"},
	{
		Timezones: []string{"America/Asuncion"},
		Code:      "PY",
		Continent: "South America",
		Name:      "Paraguay",
		Capital:   "Asunción"},
	{
		Timezones: []string{"Asia/Qatar"},
		Code:      "QA",
		Continent: "Asia",
		Name:      "Qatar",
		Capital:   "Doha"},
	{
		Timezones: []string{"Europe/Bucharest"},
		Code:      "RO",
		Continent: "Europe",
		Name:      "Romania",
		Capital:   "Bucharest"},
	{
		Timezones: []string{"Europe/Kaliningrad", "Europe/Moscow", "Europe/Volgograd", "Europe/Samara", "Asia/Yekaterinburg", "Asia/Omsk", "Asia/Novosibirsk", "Asia/Krasnoyarsk", "Asia/Irkutsk", "Asia/Yakutsk", "Asia/Vladivostok", "Asia/Sakhalin", "Asia/Magadan", "Asia/Kamchatka", "Asia/Anadyr"},
		Code:      "RU",
		Continent: "Europe",
		Name:      "Russia",
		Capital:   "Moscow"},
	{
		Timezones: []string{"Africa/Kigali"},
		Code:      "RW",
		Continent: "Africa",
		Name:      "Rwanda",
		Capital:   "Kigali"},
	{
		Timezones: []string{"Asia/Riyadh"},
		Code:      "SA",
		Continent: "Asia",
		Name:      "Saudi Arabia",
		Capital:   "Riyadh"},
	{
		Timezones: []string{"Pacific/Guadalcanal"},
		Code:      "SB",
		Continent: "Oceania",
		Name:      "Solomon Islands",
		Capital:   "Honiara"},
	{
		Timezones: []string{"Indian/Mahe"},
		Code:      "SC",
		Continent: "Africa",
		Name:      "Seychelles",
		Capital:   "Victoria"},
	{
		Timezones: []string{"Africa/Khartoum"},
		Code:      "SD",
		Continent: "Africa",
		Name:      "Sudan",
		Capital:   "Khartoum"},
	{
		Timezones: []string{"Europe/Stockholm"},
		Code:      "SE",
		Continent: "Europe",
		Name:      "Sweden",
		Capital:   "Stockholm"},
	{
		Timezones: []string{"Asia/Singapore"},
		Code:      "SG",
		Continent: "Asia",
		Name:      "Singapore",
		Capital:   "Singapore"},
	{
		Timezones: []string{"Europe/Ljubljana"},
		Code:      "SI",
		Continent: "Europe",
		Name:      "Slovenia",
		Capital:   "Ljubljana"},
	{
		Timezones: []string{"Europe/Bratislava"},
		Code:      "SK",
		Continent: "Europe",
		Name:      "Slovakia",
		Capital:   "Bratislava"},
	{
		Timezones: []string{"Africa/Freetown"},
		Code:      "SL",
		Continent: "Africa",
		Name:      "Sierra Leone",
		Capital:   "Freetown"},
	{
		Timezones: []string{"Europe/San_Marino"},
		Code:      "SM",
		Continent: "Europe",
		Name:      "San Marino",
		Capital:   "San Marino"},
	{
		Timezones: []string{"Africa/Dakar"},
		Code:      "SN",
		Continent: "Africa",
		Name:      "Senegal",
		Capital:   "Dakar"},
	{
		Timezones: []string{"Africa/Mogadishu"},
		Code:      "SO",
		Continent: "Africa",
		Name:      "Somalia",
		Capital:   "Mogadishu"},
	{
		Timezones: []string{"America/Paramaribo"},
		Code:      "SR",
		Continent: "South America",
		Name:      "Suriname",
		Capital:   "Paramaribo"},
	{
		Timezones: []string{"Africa/Sao_Tome"},
		Code:      "ST",
		Continent: "Africa",
		Name:      "São Tomé and Príncipe",
		Capital:   "São Tomé"},
	{
		Timezones: []string{"Asia/Damascus"},
		Code:      "SY",
		Continent: "Asia",
		Name:      "Syria",
		Capital:   "Damascus"},
	{
		Timezones: []string{"Africa/Lome"},
		Code:      "TG",
		Continent: "Africa",
		Name:      "Togo",
		Capital:   "Lomé"},
	{
		Timezones: []string{"Asia/Bangkok"},
		Code:      "TH",
		Continent: "Asia",
		Name:      "Thailand",
		Capital:   "Bangkok"},
	{
		Timezones: []string{"Asia/Dushanbe"},
		Code:      "TJ",
		Continent: "Asia",
		Name:      "Tajikistan",
		Capital:   "Dushanbe"},
	{
		Timezones: []string{"Asia/Ashgabat"},
		Code:      "TM",
		Continent: "Asia",
		Name:      "Turkmenistan",
		Capital:   "Ashgabat"},
	{
		Timezones: []string{"Africa/Tunis"},
		Code:      "TN",
		Continent: "Africa",
		Name:      "Tunisia",
		Capital:   "Tunis"},
	{
		Timezones: []string{"Pacific/Tongatapu"},
		Code:      "TO",
		Continent: "Oceania",
		Name:      "Tonga",
		Capital:   "Nuku'alofa"},
	{
		Timezones: []string{"Europe/Istanbul"},
		Code:      "TR",
		Continent: "Asia",
		Name:      "Turkey",
		Capital:   "Ankara"},
	{
		Timezones: []string{"America/Port_of_Spain"},
		Code:      "TT",
		Continent: "North America",
		Name:      "Trinidad and Tobago",
		Capital:   "Port of Spain"},
	{
		Timezones: []string{"Pacific/Funafuti"},
		Code:      "TV",
		Continent: "Oceania",
		Name:      "Tuvalu",
		Capital:   "Funafuti"},
	{
		Timezones: []string{"Africa/Dar_es_Salaam"},
		Code:      "TZ",
		Continent: "Africa",
		Name:      "Tanzania",
		Capital:   "Dodoma"},
	{
		Timezones: []string{"Europe/Kiev", "Europe/Uzhgorod", "Europe/Zaporozhye", "Europe/Simferopol"},
		Code:      "UA",
		Continent: "Europe",
		Name:      "Ukraine",
		Capital:   "Kiev"},
	{
		Timezones: []string{"Africa/Kampala"},
		Code:      "UG",
		Continent: "Africa",
		Name:      "Uganda",
		Capital:   "Kampala"},
	{
		Timezones: []string{"America/New_York", "America/Detroit", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Indiana/Indianapolis", "America/Indiana/Marengo", "America/Indiana/Knox", "America/Indiana/Vevay", "America/Chicago", "America/Indiana/Vincennes", "America/Indiana/Petersburg", "America/Menominee", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/Denver", "America/Boise", "America/Shiprock", "America/Phoenix", "America/Los_Angeles", "America/Anchorage", "America/Juneau", "America/Yakutat", "America/Nome", "America/Adak", "Pacific/Honolulu"},
		Code:      "US",
		Continent: "North America",
		Name:      "United States",
		Capital:   "Washington, D.C."},
	{
		Timezones: []string{"America/Montevideo"},
		Code:      "UY",
		Continent: "South America",
		Name:      "Uruguay",
		Capital:   "Montevideo"},
	{
		Timezones: []string{"Asia/Samarkand", "Asia/Tashkent"},
		Code:      "UZ",
		Continent: "Asia",
		Name:      "Uzbekistan",
		Capital:   "Tashkent"},
	{
		Timezones: []string{"Europe/Vatican"},
		Code:      "VA",
		Continent: "Europe",
		Name:      "Vatican City",
		Capital:   "Vatican City"},
	{
		Timezones: []string{"America/Caracas"},
		Code:      "VE",
		Continent: "South America",
		Name:      "Venezuela",
		Capital:   "Caracas"},
	{
		Timezones: []string{"Asia/Saigon"},
		Code:      "VN",
		Continent: "Asia",
		Name:      "Vietnam",
		Capital:   "Hanoi"},
	{
		Timezones: []string{"Pacific/Efate"},
		Code:      "VU",
		Continent: "Oceania",
		Name:      "Vanuatu",
		Capital:   "Port Vila"},
	{
		Timezones: []string{"Asia/Aden"},
		Code:      "YE",
		Continent: "Asia",
		Name:      "Yemen",
		Capital:   "Sana'a"},
	{
		Timezones: []string{"Africa/Lusaka"},
		Code:      "ZM",
		Continent: "Africa",
		Name:      "Zambia",
		Capital:   "Lusaka"},
	{
		Timezones: []string{"Africa/Harare"},
		Code:      "ZW",
		Continent: "Africa",
		Name:      "Zimbabwe",
		Capital:   "Harare"},
	{
		Timezones: []string{"Africa/Algiers"},
		Code:      "DZ",
		Continent: "Africa",
		Name:      "Algeria",
		Capital:   "Algiers"},
	{
		Timezones: []string{"Europe/Sarajevo"},
		Code:      "BA",
		Continent: "Europe",
		Name:      "Bosnia and Herzegovina",
		Capital:   "Sarajevo"},
	{
		Timezones: []string{"Asia/Phnom_Penh"},
		Code:      "KH",
		Continent: "Asia",
		Name:      "Cambodia",
		Capital:   "Phnom Penh"},
	{
		Timezones: []string{"Africa/Bangui"},
		Code:      "CF",
		Continent: "Africa",
		Name:      "Central African Republic",
		Capital:   "Bangui"},
	{
		Timezones: []string{"Africa/Ndjamena"},
		Code:      "TD",
		Continent: "Africa",
		Name:      "Chad",
		Capital:   "N'Djamena"},
	{
		Timezones: []string{"Indian/Comoro"},
		Code:      "KM",
		Continent: "Africa",
		Name:      "Comoros",
		Capital:   "Moroni"},
	{
		Timezones: []string{"Europe/Zagreb"},
		Code:      "HR",
		Continent: "Europe",
		Name:      "Croatia",
		Capital:   "Zagreb"},
	{
		Timezones: []string{"Asia/Dili"},
		Code:      "TL",
		Continent: "Asia",
		Name:      "East Timor",
		Capital:   "Dili"},
	{
		Timezones: []string{"America/El_Salvador"},
		Code:      "SV",
		Continent: "North America",
		Name:      "El Salvador",
		Capital:   "San Salvador"},
	{
		Timezones: []string{"Africa/Malabo"},
		Code:      "GQ",
		Continent: "Africa",
		Name:      "Equatorial Guinea",
		Capital:   "Malabo"},
	{
		Timezones: []string{"America/Grenada"},
		Code:      "GD",
		Continent: "North America",
		Name:      "Grenada",
		Capital:   "St. George's"},
	{
		Timezones: []string{"Asia/Almaty", "Asia/Qyzylorda", "Asia/Aqtobe", "Asia/Aqtau", "Asia/Oral"},
		Code:      "KZ",
		Continent: "Asia",
		Name:      "Kazakhstan",
		Capital:   "Astana"},
	{
		Timezones: []string{"Asia/Vientiane"},
		Code:      "LA",
		Continent: "Asia",
		Name:      "Laos",
		Capital:   "Vientiane"},
	{
		Timezones: []string{"Pacific/Truk", "Pacific/Ponape", "Pacific/Kosrae"},
		Code:      "FM",
		Continent: "Oceania",
		Name:      "Federated States of Micronesia",
		Capital:   "Palikir"},
	{
		Timezones: []string{"Europe/Chisinau"},
		Code:      "MD",
		Continent: "Europe",
		Name:      "Moldova",
		Capital:   "Chișinău"},
	{
		Timezones: []string{"Europe/Monaco"},
		Code:      "MC",
		Continent: "Europe",
		Name:      "Monaco",
		Capital:   "Monaco"},
	{
		Timezones: []string{"Europe/Podgorica"},
		Code:      "ME",
		Continent: "Europe",
		Name:      "Montenegro",
		Capital:   "Podgorica"},
	{
		Timezones: []string{"Africa/Casablanca"},
		Code:      "MA",
		Continent: "Africa",
		Name:      "Morocco",
		Capital:   "Rabat"},
	{
		Timezones: []string{"America/St_Kitts"},
		Code:      "KN",
		Continent: "North America",
		Name:      "Saint Kitts and Nevis",
		Capital:   "Basseterre"},
	{
		Timezones: []string{"America/St_Lucia"},
		Code:      "LC",
		Continent: "North America",
		Name:      "Saint Lucia",
		Capital:   "Castries"},
	{
		Timezones: []string{"America/St_Vincent"},
		Code:      "VC",
		Continent: "North America",
		Name:      "Saint Vincent and the Grenadines",
		Capital:   "Kingstown"},
	{
		Timezones: []string{"Pacific/Apia"},
		Code:      "WS",
		Continent: "Oceania",
		Name:      "Samoa",
		Capital:   "Apia"},
	{
		Timezones: []string{"Europe/Belgrade"},
		Code:      "RS",
		Continent: "Europe",
		Name:      "Serbia",
		Capital:   "Belgrade"},
	{
		Timezones: []string{"Africa/Johannesburg"},
		Code:      "ZA",
		Continent: "Africa",
		Name:      "South Africa",
		Capital:   "Pretoria"},
	{
		Timezones: []string{"Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"},
		Code:      "ES",
		Continent: "Europe",
		Name:      "Spain",
		Capital:   "Madrid"},
	{
		Timezones: []string{"Asia/Colombo"},
		Code:      "LK",
		Continent: "Asia",
		Name:      "Sri Lanka",
		Capital:   "Sri Jayewardenepura Kotte"},
	{
		Timezones: []string{"Africa/Mbabane"},
		Code:      "SZ",
		Continent: "Africa",
		Name:      "Swaziland",
		Capital:   "Mbabane"},
	{
		Timezones: []string{"Europe/Zurich"},
		Code:      "CH",
		Continent: "Europe",
		Name:      "Switzerland",
		Capital:   "Bern"},
	{
		Timezones: []string{"Asia/Dubai"},
		Code:      "AE",
		Continent: "Asia",
		Name:      "United Arab Emirates",
		Capital:   "Abu Dhabi"},
	{
		Timezones: []string{"Europe/London"},
		Code:      "GB",
		Continent: "Europe",
		Name:      "United Kingdom",
		Capital:   "London"},
	{
		Timezones: []string{"Asia/Taipei"},
		Code:      "TW",
		Continent: "Asia",
		Name:      "Taiwan",
		Capital:   "Taipei"},
	{
		Timezones: []string{"Asia/Hong_Kong"},
		Code:      "HK",
		Continent: "Asia",
		Name:      "Hong Kong",
		Capital:   "Hong Kong"},
	{
		Timezones: []string{"CET"},
		Code:      "XK",
		Continent: "Europe",
		Name:      "Kosovo",
		Capital:   "Pristina"},
	{
		Timezones: []string{"America/Puerto_Rico"},
		Code:      "PR",
		Continent: "America",
		Name:      "Puerto Rico",
		Capital:   "San Juan"},
	{
		Timezones: []string{"Europe/Mariehamn"},
		Code:      "AX",
		Name:      "Aland Islands",
		Capital:   "Mariehamn",
		Continent: "Europe"},
	{
		Timezones: []string{"Pacific/Pago_Pago"},
		Code:      "AS",
		Name:      "American Samoa",
		Capital:   "Pago Pago",
		Continent: "America"},
	{
		Timezones: []string{"America/Anguilla"},
		Code:      "AI",
		Name:      "Anguilla",
		Capital:   "The Valley",
		Continent: "America"},
	{
		Timezones: []string{"Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera", "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok"},
		Code:      "AQ",
		Name:      "Antarctica",
		Capital:   "Antarctica",
		Continent: "Antarctica"},
	{
		Timezones: []string{"America/Aruba"},
		Code:      "AW",
		Name:      "Aruba",
		Capital:   "Oranjestad",
		Continent: "America"},
	{
		Timezones: []string{"Atlantic/Bermuda"},
		Code:      "BM",
		Name:      "Bermuda",
		Capital:   "Hamilton",
		Continent: "America"},
	{
		Timezones: []string{"America/Kralendijk"},
		Code:      "BQ",
		Name:      "Bonaire, Saint Eustatius and Saba",
		Capital:   "Kralendijk",
		Continent: "America"},
	{
		Timezones: []string{"Indian/Chagos"},
		Code:      "IO",
		Name:      "British Indian Ocean Territory",
		Capital:   "Diego Garcia",
		Continent: "Africa"},
	{
		Timezones: []string{"America/Tortola"},
		Code:      "VG",
		Name:      "British Virgin Islands",
		Capital:   "Road Town",
		Continent: "America"},
	{
		Timezones: []string{"America/Cayman"},
		Code:      "KY",
		Name:      "Cayman Islands",
		Capital:   "George Town",
		Continent: "America"},
	{
		Timezones: []string{"Indian/Christmas"},
		Code:      "CX",
		Name:      "Christmas Island",
		Capital:   "Flying Fish Cove",
		Continent: "Oceania"},
	{
		Timezones: []string{"Indian/Cocos"},
		Code:      "CC",
		Name:      "Cocos Islands",
		Capital:   "West Island",
		Continent: "Oceania"},
	{
		Timezones: []string{"Pacific/Rarotonga"},
		Code:      "CK",
		Name:      "Cook Islands",
		Capital:   "Avarua",
		Continent: "Oceania"},
	{
		Timezones: []string{"America/Curacao"},
		Code:      "CW",
		Name:      "Curacao",
		Capital:   "Willemstad",
		Continent: "America"},
	{
		Timezones: []string{"Atlantic/Stanley"},
		Code:      "FK",
		Name:      "Falkland Islands",
		Capital:   "Stanley",
		Continent: "America"},
	{
		Timezones: []string{"Atlantic/Faroe"},
		Code:      "FO",
		Name:      "Faroe Islands",
		Capital:   "Tórshavn",
		Continent: "Europe"},
	{
		Timezones: []string{"America/Cayenne"},
		Code:      "GF",
		Name:      "French Guiana",
		Capital:   "Cayenne",
		Continent: "America"},
	{
		Timezones: []string{"Pacific/Gambier", "Pacific/Marquesas", "Pacific/Tahiti"},
		Code:      "PF",
		Name:      "French Polynesia",
		Capital:   "Papeetē",
		Continent: "Oceania"},
	{
		Timezones: []string{"Indian/Kerguelen"},
		Code:      "TF",
		Name:      "French Southern and Antarctic Lands",
		Capital:   "Port-aux-Français",
		Continent: "Oceania"},
	{
		Timezones: []string{"Europe/Gibraltar"},
		Code:      "GI",
		Name:      "Gibraltar",
		Capital:   "Gibraltar",
		Continent: "Europe"},
	{
		Timezones: []string{"America/Danmarkshavn", "America/Godthab", "America/Scoresbysund", "America/Thule"},
		Code:      "GL",
		Name:      "Greenland",
		Capital:   "Nuuk",
		Continent: "America"},
	{
		Timezones: []string{"America/Guadeloupe"},
		Code:      "GP",
		Name:      "Guadeloupe",
		Capital:   "Basse-Terre",
		Continent: "America"},
	{
		Timezones: []string{"Pacific/Guam"},
		Code:      "GU",
		Name:      "Guam",
		Capital:   "Hagåtña",
		Continent: "Oceania"},
	{
		Timezones: []string{"Europe/Guernsey"},
		Code:      "GG",
		Name:      "Guernsey",
		Capital:   "St. Peter Port",
		Continent: "Europe"},
	{
		Timezones: []string{"Europe/Isle_of_Man"},
		Code:      "IM",
		Name:      "Isle of Man",
		Capital:   "Douglas",
		Continent: "Europe"},
	{
		Timezones: []string{"Europe/Jersey"},
		Code:      "JE",
		Name:      "Jersey",
		Capital:   "Saint Helier",
		Continent: "Europe"},
	{
		Timezones: []string{"Asia/Macau"},
		Code:      "MO",
		Name:      "Macao",
		Capital:   "Macao",
		Continent: "Asia"},
	{
		Timezones: []string{"America/Martinique"},
		Code:      "MQ",
		Name:      "Martinique",
		Capital:   "Fort-de-France",
		Continent: "America"},
	{
		Timezones: []string{"Indian/Mayotte"},
		Code:      "YT",
		Name:      "Mayotte",
		Capital:   "Mamoudzou",
		Continent: "Africa"},
	{
		Timezones: []string{"America/Montserrat"},
		Code:      "MS",
		Name:      "Montserrat",
		Capital:   "Plymouth",
		Continent: "America"},
	{
		Timezones: []string{"Pacific/Noumea"},
		Code:      "NC",
		Name:      "New Caledonia",
		Capital:   "Nouméa",
		Continent: "Oceania"},
	{
		Timezones: []string{"Pacific/Niue"},
		Code:      "NU",
		Name:      "Niue",
		Capital:   "Alofi",
		Continent: "Oceania"},
	{
		Timezones: []string{"Pacific/Norfolk"},
		Code:      "NF",
		Name:      "Norfolk Island",
		Capital:   "Kingston",
		Continent: "Oceania"},
	{
		Timezones: []string{"Pacific/Saipan"},
		Code:      "MP",
		Name:      "Northern Mariana Islands",
		Capital:   "Saipan",
		Continent: "Oceania"},
	{
		Timezones: []string{"Asia/Gaza", "Asia/Hebron"},
		Code:      "PS",
		Name:      "Palestinian Territory",
		Capital:   "Ramallah",
		Continent: "Asia"},
	{
		Timezones: []string{"Pacific/Pitcairn"},
		Code:      "PN",
		Name:      "Pitcairn",
		Capital:   "Adamstown",
		Continent: "Oceania"},
	{
		Timezones: []string{"Indian/Reunion"},
		Code:      "RE",
		Name:      "Reunion",
		Capital:   "Saint-Denis",
		Continent: "Africa"},
	{
		Timezones: []string{"America/St_Barthelemy"},
		Code:      "BL",
		Name:      "Saint Barthelemy",
		Capital:   "Gustavia",
		Continent: "America"},
	{
		Timezones: []string{"Atlantic/St_Helena"},
		Code:      "SH",
		Name:      "Saint Helena",
		Capital:   "Jamestown",
		Continent: "Africa"},
	{
		Timezones: []string{"America/Marigot"},
		Code:      "MF",
		Name:      "Saint Martin",
		Capital:   "Marigot",
		Continent: "America"},
	{
		Timezones: []string{"America/Miquelon"},
		Code:      "PM",
		Name:      "Saint Pierre and Miquelon",
		Capital:   "Saint-Pierre",
		Continent: "America"},
	{
		Timezones: []string{"America/Lower_Princes"},
		Code:      "SX",
		Name:      "Sint Maarten",
		Capital:   "Philipsburg",
		Continent: "America"},
	{
		Timezones: []string{"Atlantic/South_Georgia"},
		Code:      "GS",
		Name:      "South Georgia and the South Sandwich Islands",
		Capital:   "King Edward Point",
		Continent: "America"},
	{
		Timezones: []string{"Africa/Juba"},
		Code:      "SS",
		Name:      "South Sudan",
		Capital:   "Juba",
		Continent: "Africa"},
	{
		Timezones: []string{"Arctic/Longyearbyen"},
		Code:      "SJ",
		Name:      "Svalbard and Jan Mayen",
		Capital:   "Longyearbyen",
		Continent: "Europe"},
	{
		Timezones: []string{"Pacific/Fakaofo"},
		Code:      "TK",
		Name:      "Tokelau",
		Capital:   "Fakaofo",
		Continent: "Oceania"},
	{
		Timezones: []string{"America/Grand_Turk"},
		Code:      "TC",
		Name:      "Turks and Caicos Islands",
		Capital:   "Cockburn Town",
		Continent: "America"},
	{
		Timezones: []string{"America/St_Thomas"},
		Code:      "VI",
		Name:      "United States Virgin Islands",
		Capital:   "Charlotte Amalie",
		Continent: "America"},
	{
		Timezones: []string{"Pacific/Midway", "Pacific/Wake"},
		Code:      "UM",
		Name:      "United States Minor Outlying Islands",
		Capital:   "United States Minor Outlying Islands",
		Continent: "America"},
	{
		Timezones: []string{"Pacific/Wallis"},
		Code:      "WF",
		Name:      "Wallis and Futuna",
		Capital:   "Mata-Utu",
		Continent: "Oceania"},
	{
		Timezones: []string{"Africa/El_Aaiun"},
		Code:      "EH",
		Name:      "Western Sahara",
		Capital:   "El Aaiún",
		Continent: "Africa",
	},
}
